### ISSUE TITLE
Factor graph cannot be a forest

### ISSUE THREAD

**Issue by TobiasMadsen** [jakob-skou-pedersen/phy#2]
Algorithms depend on the graph being connected. It is problematic when we have a structure including a "parameter variable" that is always observed, and not internally represented as a variable and thus making the graph disconnected.

**Comment by jakob-skou-pedersen** [comment]
I agree it would be good to allow disconnected graphs (a forest). To me it seems the observed parameter variable problem only occurs when they occur as inner nodes in the graph, which I guess is unusual.
